"""
Report Generation Service — Phase 20, Task 20.1

Generates intelligence reports as PDFs using ReportLab.
Supports: INCIDENT_REPORT, PERSON_REPORT, ZONE_ACTIVITY, OPERATION_SUMMARY, FORENSIC_TIMELINE
"""

import io
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.report import Report, ReportClassification, ReportStatus, ReportType

logger = logging.getLogger(__name__)

# Classification stamp colors (RGB tuples)
CLASSIFICATION_COLORS = {
    "RESTRICTED": (0.8, 0.0, 0.0),      # Red
    "CONFIDENTIAL": (0.0, 0.0, 0.8),    # Blue
    "SECRET": (0.5, 0.0, 0.5),          # Purple
}


def _generate_pdf(
    title: str,
    report_type: str,
    classification: str,
    data: Dict[str, Any],
    generated_by: str = "NSG VisionAI System",
) -> bytes:
    """
    Generate a PDF report using ReportLab.

    Args:
        title: Report title
        report_type: Report type string
        classification: Security classification
        data: Report content data
        generated_by: Name/ID of generating user

    Returns:
        PDF bytes
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate,
            Paragraph,
            Spacer,
            Table,
            TableStyle,
            HRFlowable,
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        story = []

        # Classification stamp color
        stamp_color_rgb = CLASSIFICATION_COLORS.get(classification, (0.8, 0.0, 0.0))
        stamp_color = colors.Color(*stamp_color_rgb)

        # Classification header banner
        classification_style = ParagraphStyle(
            "Classification",
            parent=styles["Normal"],
            fontSize=14,
            fontName="Helvetica-Bold",
            textColor=stamp_color,
            alignment=TA_CENTER,
            spaceAfter=6,
        )
        story.append(Paragraph(f"— {classification} —", classification_style))
        story.append(HRFlowable(width="100%", thickness=2, color=stamp_color))
        story.append(Spacer(1, 0.3 * cm))

        # Report header
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontSize=18,
            fontName="Helvetica-Bold",
            spaceAfter=6,
            alignment=TA_CENTER,
        )
        story.append(Paragraph("NSG VisionAI — Intelligence Report", title_style))
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 0.3 * cm))

        # Metadata table
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        meta_data = [
            ["Report Type:", report_type.replace("_", " ").title()],
            ["Classification:", classification],
            ["Generated By:", generated_by],
            ["Generated At:", generated_at],
        ]
        meta_table = Table(meta_data, colWidths=[4 * cm, 12 * cm])
        meta_table.setStyle(
            TableStyle([
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ])
        )
        story.append(meta_table)
        story.append(Spacer(1, 0.5 * cm))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
        story.append(Spacer(1, 0.3 * cm))

        # Summary section
        section_style = ParagraphStyle(
            "SectionHeader",
            parent=styles["Heading2"],
            fontSize=13,
            fontName="Helvetica-Bold",
            spaceBefore=12,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontSize=10,
            spaceAfter=4,
        )

        story.append(Paragraph("Executive Summary", section_style))

        summary = data.get("summary", "No summary provided.")
        story.append(Paragraph(str(summary), body_style))
        story.append(Spacer(1, 0.3 * cm))

        # Detection events section
        detection_events = data.get("detection_events", [])
        if detection_events:
            story.append(Paragraph("Detection Events", section_style))

            table_data = [["Event ID", "Type", "Feed", "Confidence", "Timestamp"]]
            for event in detection_events[:50]:  # Limit to 50 rows
                table_data.append([
                    str(event.get("id", ""))[:8] + "...",
                    str(event.get("detection_type", "")),
                    str(event.get("feed_id", ""))[:8] + "...",
                    f"{float(event.get('confidence_score', 0)):.2%}",
                    str(event.get("frame_timestamp", ""))[:19],
                ])

            events_table = Table(
                table_data,
                colWidths=[3 * cm, 3 * cm, 3 * cm, 3 * cm, 4 * cm],
            )
            events_table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.darkgrey),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                ])
            )
            story.append(events_table)
            story.append(Spacer(1, 0.3 * cm))

        # Analyst notes
        notes = data.get("analyst_notes", "")
        if notes:
            story.append(Paragraph("Analyst Notes", section_style))
            story.append(Paragraph(str(notes), body_style))
            story.append(Spacer(1, 0.3 * cm))

        # Classification footer
        story.append(Spacer(1, 0.5 * cm))
        story.append(HRFlowable(width="100%", thickness=2, color=stamp_color))
        story.append(Paragraph(f"— {classification} —", classification_style))
        story.append(
            Paragraph(
                "NSG IT Cell — Ministry of Home Affairs | Unauthorized disclosure is prohibited.",
                ParagraphStyle(
                    "Footer",
                    parent=styles["Normal"],
                    fontSize=8,
                    textColor=colors.grey,
                    alignment=TA_CENTER,
                ),
            )
        )

        doc.build(story)
        return buffer.getvalue()

    except ImportError:
        logger.warning("ReportLab not installed, generating minimal PDF placeholder")
        return _generate_minimal_pdf(title, classification)


def _generate_minimal_pdf(title: str, classification: str) -> bytes:
    """Fallback minimal PDF when ReportLab is not available."""
    content = (
        f"%PDF-1.4\n"
        f"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
        f"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
        f"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] >>\nendobj\n"
        f"% NSG VisionAI Report: {title} | Classification: {classification}\n"
        f"%%EOF\n"
    )
    return content.encode("latin-1")


class ReportService:
    """
    Service for intelligence report generation.
    Generates PDFs with classification stamps and stores in MinIO.
    """

    def __init__(self, session: AsyncSession):
        self.session = session

    async def generate_report(
        self,
        title: str,
        report_type: str,
        classification: str,
        data: Dict[str, Any],
        generated_by: UUID,
        detection_event_ids: Optional[List[str]] = None,
    ) -> Report:
        """
        Generate an intelligence report as PDF.

        Args:
            title: Report title
            report_type: One of ReportType values
            classification: One of ReportClassification values
            data: Report content (summary, events, notes, etc.)
            generated_by: UUID of requesting user
            detection_event_ids: Optional list of detection event IDs to include

        Returns:
            Created Report instance
        """
        report_id = uuid.uuid4()
        storage_path = (
            f"reports/{datetime.now(timezone.utc).strftime('%Y/%m/%d')}/{report_id}.pdf"
        )

        # Create report record as PENDING
        report = Report(
            id=report_id,
            title=title,
            report_type=report_type,
            classification=classification,
            status=ReportStatus.PENDING.value,
            generated_by=generated_by,
            generated_at=datetime.now(timezone.utc),
            detection_event_ids=detection_event_ids or [],
            file_path=storage_path,
        )
        self.session.add(report)
        await self.session.commit()
        await self.session.refresh(report)

        try:
            # Generate PDF
            pdf_bytes = _generate_pdf(
                title=title,
                report_type=report_type,
                classification=classification,
                data=data,
                generated_by=str(generated_by),
            )

            # Upload to MinIO
            try:
                from app.utils.minio_client import minio_client

                minio_client.upload_bytes(
                    data=pdf_bytes,
                    object_name=storage_path,
                    content_type="application/pdf",
                )
                logger.info("Uploaded report %s to MinIO: %s", report_id, storage_path)
            except Exception as minio_err:
                logger.warning("MinIO upload failed for report %s: %s", report_id, minio_err)
                # Continue — report record is still created

            # Mark as completed
            report.status = ReportStatus.COMPLETED.value
            await self.session.commit()

        except Exception as e:
            logger.error("Report generation failed for %s: %s", report_id, e)
            report.status = ReportStatus.FAILED.value
            await self.session.commit()

        await self.session.refresh(report)
        return report

    async def get_report(self, report_id: UUID) -> Optional[Report]:
        """Get report by ID."""
        result = await self.session.execute(
            select(Report).where(Report.id == report_id)
        )
        return result.scalar_one_or_none()

    async def list_reports(
        self,
        report_type: Optional[str] = None,
        generated_by: Optional[UUID] = None,
        skip: int = 0,
        limit: int = 50,
    ) -> List[Report]:
        """List reports with optional filters."""
        query = select(Report).order_by(Report.generated_at.desc())

        if report_type:
            query = query.where(Report.report_type == report_type)
        if generated_by:
            query = query.where(Report.generated_by == generated_by)

        query = query.offset(skip).limit(limit)
        result = await self.session.execute(query)
        return list(result.scalars().all())

    async def get_download_url(
        self, report_id: UUID, expires_seconds: int = 3600
    ) -> Optional[str]:
        """
        Get a presigned MinIO URL for report download.

        Args:
            report_id: Report UUID
            expires_seconds: URL expiry in seconds (default 1 hour)

        Returns:
            Presigned URL string or None if unavailable
        """
        report = await self.get_report(report_id)
        if report is None or report.file_path is None:
            return None

        try:
            from app.utils.minio_client import minio_client

            url = minio_client.get_presigned_url(
                object_name=report.file_path,
                expires_in=expires_seconds,
            )
            return url
        except Exception as e:
            logger.warning("Failed to generate presigned URL for report %s: %s", report_id, e)
            return None

    async def export_csv(
        self,
        report_id: UUID,
    ) -> Optional[bytes]:
        """
        Export detection event data from a report as CSV.

        Args:
            report_id: Report UUID

        Returns:
            CSV bytes or None
        """
        report = await self.get_report(report_id)
        if report is None:
            return None

        import csv
        import io as _io

        output = _io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["report_id", "title", "report_type", "classification", "generated_at", "status"])
        writer.writerow([
            str(report.id),
            report.title,
            report.report_type,
            report.classification,
            report.generated_at.isoformat() if report.generated_at else "",
            report.status,
        ])

        return output.getvalue().encode("utf-8")
