"""Report and ForensicJob repositories — Phase 4.9 / Phase 18 / Phase 20"""
from typing import List, Optional
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.report import ForensicJob, ForensicJobStatus, Report, ReportStatus
from app.repositories.base import BaseRepository


class ReportRepository(BaseRepository[Report]):
    """Repository for Report model."""

    def __init__(self, session: AsyncSession):
        super().__init__(Report, session)

    async def get_by_generated_by(
        self, user_id: UUID, skip: int = 0, limit: int = 50
    ) -> List[Report]:
        """Return reports generated by a specific user."""
        return await self.get_multi(
            skip=skip,
            limit=limit,
            filters=[Report.generated_by == user_id],
            order_by=Report.generated_at.desc(),
        )

    async def get_by_type(
        self, report_type: str, skip: int = 0, limit: int = 50
    ) -> List[Report]:
        """Return reports of a specific type."""
        return await self.get_multi(
            skip=skip,
            limit=limit,
            filters=[Report.report_type == report_type],
            order_by=Report.generated_at.desc(),
        )

    async def get_pending(self) -> List[Report]:
        """Return all reports still in PENDING state."""
        return await self.get_multi(
            filters=[Report.status == ReportStatus.PENDING.value],
            order_by=Report.generated_at.asc(),
        )


class ForensicJobRepository(BaseRepository[ForensicJob]):
    """Repository for ForensicJob model."""

    def __init__(self, session: AsyncSession):
        super().__init__(ForensicJob, session)

    async def get_by_created_by(
        self, user_id: UUID, skip: int = 0, limit: int = 50
    ) -> List[ForensicJob]:
        """Return jobs created by a specific user."""
        return await self.get_multi(
            skip=skip,
            limit=limit,
            filters=[ForensicJob.created_by == user_id],
            order_by=ForensicJob.created_at.desc(),
        )

    async def get_pending_jobs(self) -> List[ForensicJob]:
        """Return all jobs in PENDING or RUNNING state."""
        result = await self.session.execute(
            select(ForensicJob).where(
                ForensicJob.status.in_(
                    [ForensicJobStatus.PENDING.value, ForensicJobStatus.RUNNING.value]
                )
            )
        )
        return list(result.scalars().all())

    async def get_by_type(
        self, job_type: str, skip: int = 0, limit: int = 50
    ) -> List[ForensicJob]:
        """Return jobs of a specific type."""
        return await self.get_multi(
            skip=skip,
            limit=limit,
            filters=[ForensicJob.job_type == job_type],
            order_by=ForensicJob.created_at.desc(),
        )
